/**
 * Bundles src/index.ts into a single ESM file at lib/index.js.
 *
 * The DSH profile resolves @deepseek-ai/* from its own node_modules, so every
 * harness package stays external; only this plugin's own modules are inlined.
 * SKILL.md and docs/ are read at runtime by path, never bundled.
 */
import { build } from 'esbuild'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outfile = resolve(root, 'lib/index.js')

await rm(resolve(root, 'lib'), { recursive: true, force: true })
await mkdir(dirname(outfile), { recursive: true })

const result = await build({
  entryPoints: [resolve(root, 'src/index.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  sourcemap: false,
  logLevel: 'warning',
  banner: { js: '// dsh-computer-use — generated by scripts/build.mjs. Do not edit.' },
  external: [
    '@deepseek-ai/*',
    'cordis',
    '@deepseek-ai/cordis',
    '@deepseek-ai/schemastery',
  ],
  metafile: true,
})

const inputs = Object.keys(result.metafile.inputs).length
await writeFile(resolve(root, 'lib/build-meta.json'), JSON.stringify({
  inputs,
  bytes: result.metafile.outputs[Object.keys(result.metafile.outputs)[0]]?.bytes ?? 0,
}, null, 2))

console.log(`built lib/index.js from ${inputs} module(s)`)
